name: Docker Compose Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    services:
      # Redis service, since it's being used by the app
      redis:
        image: redis:latest
        ports:
          - 6379:6379

      # MySQL service
      db:
        image: mysql:5.7.22
        env:
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_USER: ${{ secrets.DB_USERNAME }}
        ports:
          - 3388:3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose

    - name: Build and run Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Run tests (optional)
      run: |
        # Aqui você pode rodar os testes no seu app ou executar outras ações
        docker exec app php artisan test

    - name: Shutdown Docker Compose
      run: |
        docker-compose down
